spring:
    datasource:
        url: jdbc:mysql://localhost/pregunta3
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        open-in-view: false
        show-sql: true
        hibernate:
            format_sql: true
            ddl-auto: create-drop
server:
    servlet.encoding.charset: UTF-8
    servlet.encoding.force: true
    error:
      include-stacktrace: on-trace-param
      include-exception: true